// packages/storybook-readme/src/env/vue/components.vue/StoryPreview.vue
<template>
  <div class="default_preview"><slot></slot></div>
</template>

<style>
.default_preview {
  position: relative;
  box-sizing: border-box;
  margin: 16px 0 16px 0;
  padding: 50px 35px;
  border: 1px dashed #e5e5e5;
  background-color: #ffffff;
  transition: background-color 0.2s;
  text-align: center;
}
</style>

// packages/storybook-readme/src/env/react/components/StoryPreview.js
import React from 'react';
import rockey from 'rockey-react';

export default rockey.div('StoryPreview')`
  position: relative;
  box-sizing: border-box;
  margin: 16px 0 16px 0;
  padding: 50px 35px;
  border: 1px dashed #e5e5e5;
  background-color: #ffffff;
  transition: background-color 0.2s;
  text-align: center;
`;
