// packages/storybook-readme/env/react/components/StoryPreview.js
var _templateObject = _taggedTemplateLiteral(
  [
    '\n  position: relative;\n  box-sizing: border-box;\n  margin: 16px 0 16px 0;\n  padding: 50px 35px;\n  border: 1px dashed #e5e5e5;\n  background-color: #ffffff;\n  transition: background-color 0.2s;\n  text-align: center;\n',
  ],
  [
    '\n  position: relative;\n  box-sizing: border-box;\n  margin: 16px 0 16px 0;\n  padding: 50px 35px;\n  border: 1px dashed #e5e5e5;\n  background-color: #ffffff;\n  transition: background-color 0.2s;\n  text-align: center;\n',
  ]
);

function _taggedTemplateLiteral(strings, raw) {
  return Object.freeze(
    Object.defineProperties(strings, { raw: { value: Object.freeze(raw) } })
  );
}

import React from 'react';
import rockey from 'rockey-react';

export default rockey.div('StoryPreview')(_templateObject);

// packages/storybook-readme/src/env/vue/components.vue/StoryPreview.vue
<template>
  <div class="default_preview"><slot></slot></div>
</template>

<style>
.default_preview {
  position: relative;
  box-sizing: border-box;
  margin: 16px 0 16px 0;
  padding: 50px 35px;
  border: 1px dashed #e5e5e5;
  background-color: #ffffff;
  transition: background-color 0.2s;
  text-align: center;
}
</style>
